# Default values for lingvis-server
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount: 1

# REQUIRED
#url: your-domain.tld

# registry:
#  url: your-registry.registry.tld/your-image

# used for the image tag
# sha: latest

app:
  port: 8080
  health: "/actuator/health"

  regcred: regcred-cuepaq

  requests:
    cpu: 10m
    memory: 128Mi
    ephemeralStorage: 1Gi

  limits:
    cpu: 2000m
    memory: 6Gi
    ephemeralStorage: 2Gi

#  pvc:
#    enabled: true
#    accessMode: ReadWriteOnce
#    storage: 5Gi
#    mountPath: "/usr/local/visargue"

  ingress:
    extraAnnotations: |
      nginx.ingress.kubernetes.io/proxy-body-size: 120m

  readinessProbe: |
    httpGet:
      path: {{ .Values.app.health }}
      port: {{ .Values.app.port }}
    initialDelaySeconds: 120
    timeoutSeconds: 5
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  livenessProbe: |
    httpGet:
      path: {{ .Values.app.health }}
      port: {{ .Values.app.port }}
    initialDelaySeconds: 120
    timeoutSeconds: 5
    periodSeconds: 5
    failureThreshold: 4
    successThreshold: 1


  # regcred: regcred

